// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Video struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	VideoUrl    string         `json:"video_url"`
	Createdat   time.Time      `json:"createdat"`
	Updatedat   time.Time      `json:"updatedat"`
}
